name: "Модуль 2, Задача 1: Игральные кости"

env:
  FOLDER_WITH_TASK: "Module 2/2. images-galery"

on:
  push:
    paths:
      - "Module 2/2. images-galery/**"

jobs:
  test:
    name: Запускаем тесты
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        working-directory: ${{ env.FOLDER_WITH_TASK }}
        run: npm install
      - name: Run tests
        working-directory: ${{ env.FOLDER_WITH_TASK }}
        run: npm test
