name: "Модуль 3, Задача 1: Список товаров"

env:
  FOLDER_WITH_TASK: "Module 3/1. products-list"

on:
  push:
    paths:
      - "Module 3/1. products-list/**"

jobs:
  test:
    name: Запускаем тесты
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        working-directory: ${{ env.FOLDER_WITH_TASK }}
        run: npm install
      - name: Run tests
        working-directory: ${{ env.FOLDER_WITH_TASK }}
        run: npm test
